#!/bin/sh
# git-svn/svn commit

GitSvn="false"
set +e
git svn info > /dev/null
if [[ "$?" = "0" ]];then
    GitSvn="true"
fi
set -e
echo="echo"
function DoCommit()
{
    file="$1"
    msg="$2"
    ${echo} "is Git-Svn repository? ${GitSvn}"
    if [[ "${GitSvn}x" = "truex" ]];then
        git add --force -- ${file}
        git commit -m "${msg}"
        stashmsg=$(git stash)
        git svn dcommit
        ${echo} "is stashed something? ${stashmsg:0:5}"
        if [[ "${stashmsg:0:5}" = "Saved" ]];then
           git stash pop 
        fi
    else
        svn add --force --depth infinity -- ${file}
        svn commit --username "${svnuname}" --password "${svnpword}" -m "${msg}" -- ${file}
    fi
    ${echo} "auto commit: ${msg} ${file}"
}

############ main ############  
DoCommit "$1" "$2"
