#!/bin/sh

function ResetExitOnErr()
{
    set -e
}
function ResetDebug()
{
    set +x
}

if [[ "${#@}" = "0" ]];then
echo -e "usage: genAB [-BKUC] [-R [OssBucketRoot]] --A3Channel channel 
     -B|--BuildAB               Build asset bundle
     --A3Channel channel        A3Channel
     -K|--KillUnity             Kill Unity process
     -U|--UploadProduct         Upload asset bundle to oss
     -R|--OssBucketRoot rname   bucket_root
 "
     exit 1
 fi

temp=$(getopt -o BKUR:C --long BuildAB,Kill,UploadProduct,OssBucketRoot:Clean,A3Channel: -- "$@")
if [ $? != 0  ] ; then 
    echo "terminating..." >&2 
    exit 1 
fi
eval set -- "$temp"

while true;do
    case "$1" in
    --A3Channel)
        A3Channel="$2";
        shift 2
    ;;
    -B|--BuildAB) 
        BuildAB="true"; 
        shift
    ;;
    -K|--Kill) 
        KillUnity="true"; 
        shift
    ;;
    -R|--OssBucketRoot)
        OssBucketRoot="$2"; 
        shift 2
    ;;
    -U|--UploadProduct) 
        UploadProduct="true"; 
        shift
    ;;
    -C|--Clean) 
        Clean="true"; 
        shift
    ;;
    --) 
        shift;
        break
    ;;
    *) 
        echo -e "unknow arg:[$1]"; 
        shift
    ;;
    esac
done

set +x
source ~/.bash_pw
ResetDebug

aloss="${aloss-aliyuncli oss}"

BuildAB="${BuildAB-false}"
UploadProduct="${UploadProduct-false}"
KillUnity="${KillUnity-false}" 
Clean="${Clean-false}"
OssBucketRoot="${OssBucketRoot-${ossa3prod}}"
A3Channel=${A3Channel-"ios_bili_cb1"}
A3Channel=${A3Channel%#*}

function SetColor()
{
    Reset='\033[00m'
    Red='\033[01;31m'
    Green='\033[01;32m'
    Yellow='\033[01;33m'
    Purple='\033[01;35m'
    Cyan='\033[01;36m'
    White='\033[01;37m'
    Bold='\033[1m'
    Underline='\033[4m'
}

if [[ "${JENKINS_HOME}x" = "x" ]];then
    SetColor
    echo="echo -e"
else
    echo="echo"
fi

if [[ ! -d "Assets" ]]; then
   ${echo} "${Red}Not an Unity project dir${Reset}" 
   ${echo} "${Yellow}Place run in an Unity project dir with an \"Assets\"${Reset}"
   exit 1
fi

function DoBuildAB()
{
	set +e
    if [[ "${KillUnity}x" = "truex" ]];then
        ${echo} "kill all unity"
        killall Unity
    fi
	# ClearBuild
	if [[ "${Clean}x" = "truex" ]];then
		Unity -projectPath "$(pwd)" \
		        -quit \
		        -batchmode \
		        -executeMethod "Project.AssetBundleBuildManager.ClearBuildCli" \
		        -logFile "/dev/stdout"
		
		\rm -rf "$(pwd)/Assets/Application/Editor/Project/AssetBundle/Work/"*
		\rm -rf "$(pwd)/AssetBundle/"*
	fi

	# BuildCli
	Unity -projectPath "$(pwd)" \
	        -quit \
	        -batchmode \
	        -executeMethod "Project.AssetBundleBuildManager.BuildCli" \
	        -logFile "/dev/stdout"
    ResetExitOnErr	
}

function DoUploadOss()
{
	pushd "AssetBundle/Main"

    local logout="/dev/null"
    if [[ "${JENKINS_HOME}x" = "x" ]];then
        logout="/dev/stdout"
    fi
    ${echo} "Upload to oss ..."
    local bucketPath="${OssBucketRoot}/${A3Channel/*_}/master"
	ls -r | while read l;do
        ${echo} "oss putting ${l} => ${bucketPath}/${l} ..."
		$aloss UploadDisk "${l}" "${bucketPath}/" \
            --content_type "application/octet-stream" \
            --device_id 1 > "${logout}"
	done

    ${echo} "Upload to oss done"
    popd
}

################################ main ################################

set +x
source ~/.bash_pw
ResetDebug

${echo} "Build AssetBundle? ${BuildAB}"
if [[ "${BuildAB}x" = "truex" ]];then
    DoBuildAB
fi

${echo} "Upload AssetBundle to oss? ${UploadProduct}"
if [[ "${UploadProduct}x" = "truex" ]];then
	DoUploadOss
fi
