#!/bin/sh

## start jenkins
function StartJenkins(){
    echo "start jenkins ..."
    mkdir -p ~/jenkins
    pushd ~/jenkins
    killN jenkins > /dev/null
    nohup java -jar jenkins.war > nohup.jenkins 2>&1 &
    popd
    echo "start jenkins end $?\n"
}

## start http:80
function StartHttp80(){
    echo "start http ..."
    mkdir -p ~/http
    #pushd ~/http
    killN http.server > /dev/null
    nohup sudo python3 -m http.server 80 > ~/http/nohup.http 2>&1 &
    #popd
    echo "start http end $?\n"
}

## start CacheServer
function StartCacheServer(){
    echo "start CacheServer ..."
    pushd ~/.jenkins/workspace/CacheServer
    killN node
    nohup ./RunOSX.sh 2>&1  &
    popd 
    echo "start CacheServer done"
}
########## main ########## 

#StartJenkins

StartHttp80

StartCacheServer

